import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Inter } from "next/font/google";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="absolute top-4 right-4 space-x-4">
          <a href="/signin" className="text-blue-500 hover:underline">Sign In</a>
          <a href="/register" className="text-blue-500 hover:underline">Register</a>
        </div>
        {children}
      </body>
    </html>
  );
}
